### ISSUE TITLE
"looks like some samples are not valid"

### ISSUE THREAD

**Issue by reyesnv** [phac-nml/irida-miseq-uploader#4]
IRIDA detects one of my samples as not valid - "missing fastq files" 
I've encountered this before but with help of Illumina tech support, it was fixed. I couldn't remember what I did before to resolve the issue. They are closed today. Can someone please help?

**Comment by tom114** [comment]
Hi there,

Generally when that error occurs is because of exactly what the error states: that there's missing fastq files for a sample listed in the SampleSheet.csv file.  Start by looking at which sample it states is missing files, then look in the `Data/Intensities/BaseCalls` folder to ensure fastq files exist for all those samples.

If all the files exist there, we've once found an example of a run where a second SampleSheet.csv file was copied into a subfolder of the run.  Ensure there are no other copies of SampleSheet.csv within the run folder you're trying to upload.

Let us know how it works out.

**Comment by reyesnv** [comment]
Hey, it's resolved now. I just had to match the actual fastq file generated tags to the sample sheet. Like if the fastq file was "E-coli...." then the sample sheet has to be "E-coli..." as well. I clicked scan again and it had detected it.
